<?php

function mymodule_preprocess_page(&$variables) {
  $variables['#attached']['library'][] =  'mymodule/mymodule-lib';
}

function mymodule_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];
  $field = $variables['field'];
 
  if ($view->storage->id() == 'courses' && $view->current_display == 'page_1' && $field->field == 'field_link_to_subscribe') {
    $nid = $variables['row']->nid;
    $values = \Drupal::entityQuery('node')
      ->condition('field_course', $nid)
      ->condition('uid', \Drupal::currentUser()->id())
      ->execute();
    if(!empty($values)){
      $link = '<a href="/lms/subscribe/'.$nid.'">Unsubscribe</a>';
    } else {
      $link = '<a href="/lms/subscribe/'.$nid.'">Subscribe</a>';
    }
    $variables['output'] =  [
        '#markup' => $link,
      ];
  }
}

?>
